name: "Espionage Entity Schemas"
description: "Entity field schemas optimized for intelligence and covert operations"
version: "1.0"
author: "PyScrAI Team"
genre: "espionage"

schemas:
  actor:
    name: "Real name"
    alias: "Operational aliases or code names"
    cover_identity: "Cover identity or legend"
    rank: "Rank or position in organization"
    organization: "Intelligence agency, group, or cell"
    specialty: "Area of expertise (infiltration, hacking, linguistics, etc)"
    status: "Current operational status (active, compromised, captured, etc)"
    handler: "Intelligence handler or supervisor"
    operations: "Known operations or assignments"
    description: "Profile or background"
    tags: "Categories (operative, handler, target, etc)"
  
  polity:
    name: "Organization name"
    type: "Type (intelligence agency, criminal syndicate, terrorist group, cell, etc)"
    acronym: "Acronym or abbreviation (CIA, FSB, etc)"
    country: "Country or region of origin"
    leadership: "Known leaders or commanders"
    structure: "Organizational structure (cells, departments, etc)"
    operatives: "Known members or operatives"
    capabilities: "Known capabilities or specialties"
    status: "Operational status (active, dismantled, compromised)"
    description: "Organization overview"
    tags: "Categories (state, private, criminal, etc)"
  
  location:
    name: "Location name or identifier"
    type: "Type (safe house, base, embassy, dead drop, etc)"
    location: "Geographic location or address (if safe to reveal)"
    status: "Operational status (active, compromised, burned, etc)"
    operator: "Who controls or operates it"
    access: "How to access or approach"
    equipment: "Communications or equipment available"
    capacity: "How many people it can support"
    description: "Operational details"
    tags: "Categories (safe house, weapons cache, etc)"
  
  abstract:
    name: "Operation or mission name"
    type: "Type (operation, mission, protocol, network, etc)"
    codename: "Operational code name"
    objective: "Mission objective"
    status: "Current status (active, completed, compromised, etc)"
    participants: "Operatives or agencies involved"
    timeline: "When it occurred or is scheduled"
    outcome: "Result or current progress"
    description: "Operation details"
    tags: "Categories (active, surveillance, infiltration, etc)"

metadata:
  compatible_genres: ["espionage", "intelligence", "covert", "classified"]
  entity_types: ["actor", "polity", "location", "abstract"]
  focus: "Aliases, handlers, status, operational details, security"
  security_level: "Sensitive - contains operational and asset information"
  created_at: "2026-01-04"
