name: "Historical Entity Schemas"
description: "Entity field schemas optimized for historical documents"
version: "1.0"
author: "PyScrAI Team"
genre: "historical"

schemas:
  actor:
    name: "Full name or regnal name"
    title: "Royal title, rank, or honorific (King, General, etc)"
    birth_date: "Birth year or period"
    death_date: "Death year or period"
    role: "Political or military role"
    affiliation: "Kingdom, realm, or faction"
    description: "Biography or historical significance"
    accomplishments: "Notable deeds or achievements"
    conflicts: "Wars, disputes, or feuds involved in"
    tags: "Categories (ruler, general, noble, etc)"
  
  polity:
    name: "Name of kingdom, empire, or state"
    type: "Political entity type (kingdom, empire, city-state, etc)"
    period: "Historical period when it existed (e.g., 1066-1485)"
    capital: "Capital city or seat of power"
    rulers: "Known monarchs or rulers"
    territory: "Approximate territory or lands controlled"
    government_type: "Government structure (absolute, constitutional, etc)"
    description: "History and significance"
    allies: "Allied kingdoms or states"
    enemies: "Rival or enemy powers"
    tags: "Categories (medieval, ancient, etc)"
  
  location:
    name: "Historical name of place"
    type: "Type (kingdom, city, battle site, region, etc)"
    period: "Historical period (when relevant)"
    significance: "Historical importance"
    description: "Geographic and historical context"
    ruler: "Who controlled or ruled it"
    conflicts: "Battles or sieges that occurred there"
    tags: "Categories"
  
  abstract:
    name: "Event, treaty, or period name"
    type: "Type (war, treaty, movement, era, etc)"
    date: "When it occurred or period"
    participants: "Parties involved"
    outcome: "Result or consequence"
    significance: "Historical impact"
    description: "Detailed description"
    tags: "Categories"

metadata:
  compatible_genres: ["historical", "chronicle", "biography"]
  entity_types: ["actor", "polity", "location", "abstract"]
  focus: "Historical accuracy, dates, titles, relationships between rulers"
  created_at: "2026-01-04"
